<div class="container">
  
  <ul class="nav nav-tabs">
    
    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>
  </ul>

  <div class="tab-content">
    <div id="menu1" class="tab-pane fade">
     <span class="pointer" value="angry_face.png" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/angry_face.png')"><img src="http://visteco.in/images/emoticons/angry_face.png"></span>
     <span class="pointer" value="angry_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/angry_face.svg')"><img src="http://visteco.in/images/emoticons/angry_face.svg"></span>
     <span class="pointer" value="anguished_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/anguished_face.svg')"><img src="http://visteco.in/images/emoticons/anguished_face.svg"></span>
     <span class="pointer" value="astonished_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/astonished_face.svg')"><img src="http://visteco.in/images/emoticons/astonished_face.svg"></span>
     <span class="pointer" value="athletic_shoe.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/athletic_shoe.svg')"><img src="http://visteco.in/images/emoticons/athletic_shoe.svg"></span>
     <span class="pointer" value="baby_angel.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/baby_angel.svg')"><img src="http://visteco.in/images/emoticons/baby_angel.svg"></span>
     <span class="pointer" value="baby.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/baby.svg')"><img src="http://visteco.in/images/emoticons/baby.svg"></span>
     <span class="pointer" value="bikini.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/bikini.svg')"><img src="http://visteco.in/images/emoticons/bikini.svg"></span>
     <span class="pointer" value="boy.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/boy.svg')"><img src="http://visteco.in/images/emoticons/boy.svg"></span>
     <span class="pointer" value="bride_with_veil.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/bride_with_veil.svg')"><img src="http://visteco.in/images/emoticons/bride_with_veil.svg"></span>
     <span class="pointer" value="briefcase.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/briefcase.svg')"><img src="http://visteco.in/images/emoticons/briefcase.svg"></span>
     <span class="pointer" value="bust_in_silhouette.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/bust_in_silhouette.svg')"><img src="http://visteco.in/images/emoticons/bust_in_silhouette.svg"></span>
     <span class="pointer" value="busts_in_silhouette.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/busts_in_silhouette.svg')"><img src="http://visteco.in/images/emoticons/busts_in_silhouette.svg"></span>
     <span class="pointer" value="call_me_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/call_me_hand.svg')"><img src="http://visteco.in/images/emoticons/call_me_hand.svg"></span>
                                            
    </div>
    <div id="menu2" class="tab-pane fade">
      <span class="pointer" value="cat_face_with_tears_of_joy.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/cat_face_with_tears_of_joy.svg')"><img src="http://visteco.in/images/emoticons/cat_face_with_tears_of_joy.svg"></span>
                                        <span class="pointer" value="cat_face_with_wry_smile.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/cat_face_with_wry_smile.svg')"><img src="http://visteco.in/images/emoticons/cat_face_with_wry_smile.svg"></span>
                                        <span class="pointer" value="clapping_hands_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/clapping_hands_sign.svg')"><img src="http://visteco.in/images/emoticons/clapping_hands_sign.svg"></span>
                                        <span class="pointer" value="closed_umbrella.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/closed_umbrella.svg')"><img src="http://visteco.in/images/emoticons/closed_umbrella.svg"></span>
                                        <span class="pointer" value="confounded_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/confounded_face.svg')"><img src="http://visteco.in/images/emoticons/confounded_face.svg"></span>
                                        <span class="pointer" value="confused_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/confused_face.svg')"><img src="http://visteco.in/images/emoticons/confused_face.svg"></span>
                                        <span class="pointer" value="construction_worker.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/construction_worker.svg')"><img src="http://visteco.in/images/emoticons/construction_worker.svg"></span>
                                        <span class="pointer" value="couple_(man,man).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/couple_(man,man).svg')"><img src="http://visteco.in/images/emoticons/couple_(man,man).svg"></span>
                                        <span class="pointer" value="couple_with_heart.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/couple_with_heart.svg')"><img src="http://visteco.in/images/emoticons/couple_with_heart.svg"></span>
                                        <span class="pointer" value="couple_(woman,woman).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/couple_(woman,woman).svg')"><img src="http://visteco.in/images/emoticons/couple_(woman,woman).svg"></span>
                                        <span class="pointer" value="crown.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/crown.svg')"><img src="http://visteco.in/images/emoticons/crown.svg"></span>
                                        <span class="pointer" value="crying_cat_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/crying_cat_face.svg')"><img src="http://visteco.in/images/emoticons/crying_cat_face.svg"></span>
                                        <span class="pointer" value="crying_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/crying_face.svg')"><img src="http://visteco.in/images/emoticons/crying_face.svg"></span>
                                        <span class="pointer" value="dancer.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/dancer.svg')"><img src="http://visteco.in/images/emoticons/dancer.svg"></span>
                                        <span class="pointer" value="dark_sunglasses.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/dark_sunglasses.svg')"><img src="http://visteco.in/images/emoticons/dark_sunglasses.svg"></span>
                                        <span class="pointer" value="disappointed_but_relieved_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/disappointed_but_relieved_face.svg')"><img src="http://visteco.in/images/emoticons/disappointed_but_relieved_face.svg"></span>
                                        <span class="pointer" value="disappointed_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/disappointed_face.svg')"><img src="http://visteco.in/images/emoticons/disappointed_face.svg"></span>
                                        <span class="pointer" value="dizzy_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/dizzy_face.svg')"><img src="http://visteco.in/images/emoticons/dizzy_face.svg"></span>
                                        <span class="pointer" value="dress.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/dress.svg')"><img src="http://visteco.in/images/emoticons/dress.svg"></span>
                                        <span class="pointer" value="ear.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/ear.svg')"><img src="http://visteco.in/images/emoticons/ear.svg"></span>
                                        <span class="pointer" value="expressionless_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/expressionless_face.svg')"><img src="http://visteco.in/images/emoticons/expressionless_face.svg"></span>
                                        <span class="pointer" value="extraterrestrial_alien.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/extraterrestrial_alien.svg')"><img src="http://visteco.in/images/emoticons/extraterrestrial_alien.svg"></span>
    </div>
    <div id="menu3" class="tab-pane fade">
      <span class="pointer" value="eyeglasses.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/eyeglasses.svg')"><img src="http://visteco.in/images/emoticons/eyeglasses.svg"></span>
                                            <span class="pointer" value="eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/eyes.svg')"><img src="http://visteco.in/images/emoticons/eyes.svg"></span>
                                            <span class="pointer" value="eye.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/eye.svg')"><img src="http://visteco.in/images/emoticons/eye.svg"></span>
                                            <span class="pointer" value="face_massage.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_massage.svg')"><img src="http://visteco.in/images/emoticons/face_massage.svg"></span>
                                            <span class="pointer" value="face_palm.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_palm.svg')"><img src="http://visteco.in/images/emoticons/face_palm.svg"></span>
                                            <span class="pointer" value="face_savouring_delicious_food.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_savouring_delicious_food.svg')"><img src="http://visteco.in/images/emoticons/face_savouring_delicious_food.svg"></span>
                                            <span class="pointer" value="face_screaming_in_fear.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_screaming_in_fear.svg')"><img src="http://visteco.in/images/emoticons/face_screaming_in_fear.svg"></span>
                                            <span class="pointer" value="face_throwing_a_kiss.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_throwing_a_kiss.svg')"><img src="http://visteco.in/images/emoticons/face_throwing_a_kiss.svg"></span>
                                            <span class="pointer" value="face_with_cold_sweat.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_cold_sweat.svg')"><img src="http://visteco.in/images/emoticons/face_with_cold_sweat.svg"></span>
                                            <span class="pointer" value="face_with_head-bandage.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_head-bandage.svg')"><img src="http://visteco.in/images/emoticons/face_with_head-bandage.svg"></span>
                                            <span class="pointer" value="face_with_look_of_triumph.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_look_of_triumph.svg')"><img src="http://visteco.in/images/emoticons/face_with_look_of_triumph.svg"></span>
                                            <span class="pointer" value="face_with_medical_mask.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_medical_mask.svg')"><img src="http://visteco.in/images/emoticons/face_with_medical_mask.svg"></span>
                                            <span class="pointer" value="face_with_no_good_gesture.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_no_good_gesture.svg')"><img src="http://visteco.in/images/emoticons/face_with_no_good_gesture.svg"></span>
                                            <span class="pointer" value="face_with_ok_gesture.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_ok_gesture.svg')"><img src="http://visteco.in/images/emoticons/face_with_ok_gesture.svg"></span>
                                            <span class="pointer" value="face_with_open_mouth_and_cold_sweat.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_open_mouth_and_cold_sweat.svg')"><img src="http://visteco.in/images/emoticons/face_with_open_mouth_and_cold_sweat.svg"></span>
                                            <span class="pointer" value="face_with_open_mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_open_mouth.svg')"><img src="http://visteco.in/images/emoticons/face_with_open_mouth.svg"></span>
                                            <span class="pointer" value="face_without_mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_without_mouth.svg')"><img src="http://visteco.in/images/emoticons/face_without_mouth.svg"></span>
                                            <span class="pointer" value="face_with_rolling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_rolling_eyes.svg')"><img src="http://visteco.in/images/emoticons/face_with_rolling_eyes.svg"></span>
                                            <span class="pointer" value="face_with_stuck-out_tongue_and_tightly-closed_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_stuck-out_tongue_and_tightly-closed_eyes.svg')"><img src="http://visteco.in/images/emoticons/face_with_stuck-out_tongue_and_tightly-closed_eyes.svg"></span>
                                            <span class="pointer" value="face_with_stuck-out_tongue_and_winking_eye.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_stuck-out_tongue_and_winking_eye.svg')"><img src="http://visteco.in/images/emoticons/face_with_stuck-out_tongue_and_winking_eye.svg"></span>
                                            <span class="pointer" value="face_with_stuck-out_tongue.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_stuck-out_tongue.svg')"><img src="http://visteco.in/images/emoticons/face_with_stuck-out_tongue.svg"></span>
                                            <span class="pointer" value="face_with_tears_of_joy.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_tears_of_joy.svg')"><img src="http://visteco.in/images/emoticons/face_with_tears_of_joy.svg"></span>
                                            <span class="pointer" value="face_with_thermometer.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/face_with_thermometer.svg')"><img src="http://visteco.in/images/emoticons/face_with_thermometer.svg"></span>
                                            <span class="pointer" value="family_(man,man,boy,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,man,boy,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(man,man,boy,boy).svg"></span>
                                            <span class="pointer" value="family_(man,man,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,man,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(man,man,boy).svg"></span>
                                            <span class="pointer" value="family_(man,man,girl,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,man,girl,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(man,man,girl,boy).svg"></span>
                                            <span class="pointer" value="family_(man,man,girl,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,man,girl,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(man,man,girl,girl).svg"></span>
                                            <span class="pointer" value="family_(man,man,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,man,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(man,man,girl).svg"></span>
                                            <span class="pointer" value="family_(man,woman,boy,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,woman,boy,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(man,woman,boy,boy).svg"></span>
                                            <span class="pointer" value="family_(man,woman,girl,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,woman,girl,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(man,woman,girl,boy).svg"></span>
                                            <span class="pointer" value="family_(man,woman,girl,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,woman,girl,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(man,woman,girl,girl).svg"></span>
                                            <span class="pointer" value="family_(man,woman,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(man,woman,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(man,woman,girl).svg"></span>
                                            <span class="pointer" value="family.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family.svg')"><img src="http://visteco.in/images/emoticons/family.svg"></span>
                                            <span class="pointer" value="family_(woman,woman,boy,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(woman,woman,boy,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(woman,woman,boy,boy).svg"></span>
                                            <span class="pointer" value="family_(woman,woman,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(woman,woman,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(woman,woman,boy).svg"></span>
                                            <span class="pointer" value="family_(woman,woman,girl,boy).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(woman,woman,girl,boy).svg')"><img src="http://visteco.in/images/emoticons/family_(woman,woman,girl,boy).svg"></span>
                                            <span class="pointer" value="family_(woman,woman,girl,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(woman,woman,girl,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(woman,woman,girl,girl).svg"></span>
                                            <span class="pointer" value="family_(woman,woman,girl).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/family_(woman,woman,girl).svg')"><img src="http://visteco.in/images/emoticons/family_(woman,woman,girl).svg"></span>
                                            <span class="pointer" value="father_christmas.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/father_christmas.svg')"><img src="http://visteco.in/images/emoticons/father_christmas.svg"></span>
                                            <span class="pointer" value="fearful_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/fearful_face.svg')"><img src="http://visteco.in/images/emoticons/fearful_face.svg"></span>
                                            <span class="pointer" value="fisted_hand_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/fisted_hand_sign.svg')"><img src="http://visteco.in/images/emoticons/fisted_hand_sign.svg"></span>
                                            <span class="pointer" value="flexed_biceps.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/flexed_biceps.svg')"><img src="http://visteco.in/images/emoticons/flexed_biceps.svg"></span>
                                            <span class="pointer" value="flushed_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/flushed_face.svg')"><img src="http://visteco.in/images/emoticons/flushed_face.svg"></span>
                                            <span class="pointer" value="footprints.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/footprints.svg')"><img src="http://visteco.in/images/emoticons/footprints.svg"></span>
                                            <span class="pointer" value="frowning_face_with_open_mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/frowning_face_with_open_mouth.svg')"><img src="http://visteco.in/images/emoticons/frowning_face_with_open_mouth.svg"></span>
                                            <span class="pointer" value="ghost.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/ghost.svg')"><img src="http://visteco.in/images/emoticons/ghost.svg"></span>
                                            <span class="pointer" value="girl.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/girl.svg')"><img src="http://visteco.in/images/emoticons/girl.svg"></span>
                                            <span class="pointer" value="graduation_cap.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/graduation_cap.svg')"><img src="http://visteco.in/images/emoticons/graduation_cap.svg"></span>
                                            <span class="pointer" value="grimacing_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/grimacing_face.svg')"><img src="http://visteco.in/images/emoticons/grimacing_face.svg"></span>
                                            <span class="pointer" value="grinning_cat_face_with_smiling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/grinning_cat_face_with_smiling_eyes.svg')"><img src="http://visteco.in/images/emoticons/grinning_cat_face_with_smiling_eyes.svg"></span>
                                            <span class="pointer" value="grinning_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/grinning_face.svg')"><img src="http://visteco.in/images/emoticons/grinning_face.svg"></span>
                                            <span class="pointer" value="grinning_face_with_smiling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/grinning_face_with_smiling_eyes.svg')"><img src="http://visteco.in/images/emoticons/grinning_face_with_smiling_eyes.svg"></span>
                                            <span class="pointer" value="guardsman.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/guardsman.svg')"><img src="http://visteco.in/images/emoticons/guardsman.svg"></span>
                                            <span class="pointer" value="haircut.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/haircut.svg')"><img src="http://visteco.in/images/emoticons/haircut.svg"></span>
                                            <span class="pointer" value="handbag.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/handbag.svg')"><img src="http://visteco.in/images/emoticons/handbag.svg"></span>
                                            <span class="pointer" value="handshake.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/handshake.svg')"><img src="http://visteco.in/images/emoticons/handshake.svg"></span>
                                            <span class="pointer" value="hand_with_first_and_index_finger_crossed.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/hand_with_first_and_index_finger_crossed.svg')"><img src="http://visteco.in/images/emoticons/hand_with_first_and_index_finger_crossed.svg"></span>
                                            <span class="pointer" value="happy_person_raising_one_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/happy_person_raising_one_hand.svg')"><img src="http://visteco.in/images/emoticons/happy_person_raising_one_hand.svg"></span>
                                            <span class="pointer" value="helmet_with_white_cross.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/helmet_with_white_cross.svg')"><img src="http://visteco.in/images/emoticons/helmet_with_white_cross.svg"></span>
                                            <span class="pointer" value="high-heeled_shoe.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/high-heeled_shoe.svg')"><img src="http://visteco.in/images/emoticons/high-heeled_shoe.svg"></span>
                                            <span class="pointer" value="hugging_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/hugging_face.svg')"><img src="http://visteco.in/images/emoticons/hugging_face.svg"></span>
                                            <span class="pointer" value="hushed_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/hushed_face.svg')"><img src="http://visteco.in/images/emoticons/hushed_face.svg"></span>
                                            <span class="pointer" value="imp.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/imp.svg')"><img src="http://visteco.in/images/emoticons/imp.svg"></span>
                                            <span class="pointer" value="information_desk_person.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/information_desk_person.svg')"><img src="http://visteco.in/images/emoticons/information_desk_person.svg"></span>
                                            <span class="pointer" value="japanese_goblin.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/japanese_goblin.svg')"><img src="http://visteco.in/images/emoticons/japanese_goblin.svg"></span>
                                            <span class="pointer" value="japanese_ogre.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/japanese_ogre.svg')"><img src="http://visteco.in/images/emoticons/japanese_ogre.svg"></span>
                                            <span class="pointer" value="jeans.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/jeans.svg')"><img src="http://visteco.in/images/emoticons/jeans.svg"></span>
                                            <span class="pointer" value="kimono.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kimono.svg')"><img src="http://visteco.in/images/emoticons/kimono.svg"></span>
                                            <span class="pointer" value="kissing_cat_face_with_closed_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kissing_cat_face_with_closed_eyes.svg')"><img src="http://visteco.in/images/emoticons/kissing_cat_face_with_closed_eyes.svg"></span>
                                            <span class="pointer" value="kissing_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kissing_face.svg')"><img src="http://visteco.in/images/emoticons/kissing_face.svg"></span>
                                            <span class="pointer" value="kissing_face_with_closed_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kissing_face_with_closed_eyes.svg')"><img src="http://visteco.in/images/emoticons/kissing_face_with_closed_eyes.svg"></span>
                                            <span class="pointer" value="kissing_face_with_smiling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kissing_face_with_smiling_eyes.svg')"><img src="http://visteco.in/images/emoticons/kissing_face_with_smiling_eyes.svg"></span>
                                            <span class="pointer" value="kiss_(man,man).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kiss_(man,man).svg')"><img src="http://visteco.in/images/emoticons/kiss_(man,man).svg"></span>
                                            <span class="pointer" value="kiss_mark.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kiss_mark.svg')"><img src="http://visteco.in/images/emoticons/kiss_mark.svg"></span>
                                            <span class="pointer" value="kiss.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kiss.svg')"><img src="http://visteco.in/images/emoticons/kiss.svg"></span>
                                            <span class="pointer" value="kiss_(woman,woman).svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/kiss_(woman,woman).svg')"><img src="http://visteco.in/images/emoticons/kiss_(woman,woman).svg"></span>
                                            <span class="pointer" value="left-facing_fist.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/left-facing_fist.svg')"><img src="http://visteco.in/images/emoticons/left-facing_fist.svg"></span>
                                            <span class="pointer" value="lipstick.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/lipstick.svg')"><img src="http://visteco.in/images/emoticons/lipstick.svg"></span>
                                            <span class="pointer" value="loudly_crying_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/loudly_crying_face.svg')"><img src="http://visteco.in/images/emoticons/loudly_crying_face.svg"></span>
                                            <span class="pointer" value="man_and_woman_holding_hands.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man_and_woman_holding_hands.svg')"><img src="http://visteco.in/images/emoticons/man_and_woman_holding_hands.svg"></span>
                                            <span class="pointer" value="man_dancing.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man_dancing.svg')"><img src="http://visteco.in/images/emoticons/man_dancing.svg"></span>
                                            <span class="pointer" value="man_in_tuxedo.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man_in_tuxedo.svg')"><img src="http://visteco.in/images/emoticons/man_in_tuxedo.svg"></span>
                                            <span class="pointer" value="mans_shoe.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/mans_shoe.svg')"><img src="http://visteco.in/images/emoticons/mans_shoe.svg"></span>
                                            <span class="pointer" value="man.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man.svg')"><img src="http://visteco.in/images/emoticons/man.svg"></span>
                                            <span class="pointer" value="man_with_gua_pi_mao.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man_with_gua_pi_mao.svg')"><img src="http://visteco.in/images/emoticons/man_with_gua_pi_mao.svg"></span>
                                            <span class="pointer" value="man_with_turban.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/man_with_turban.svg')"><img src="http://visteco.in/images/emoticons/man_with_turban.svg"></span>
                                            <span class="pointer" value="money-mouth_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/money-mouth_face.svg')"><img src="http://visteco.in/images/emoticons/money-mouth_face.svg"></span>
                                            <span class="pointer" value="mother_christmas.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/mother_christmas.svg')"><img src="http://visteco.in/images/emoticons/mother_christmas.svg"></span>
                                            <span class="pointer" value="mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/mouth.svg')"><img src="http://visteco.in/images/emoticons/mouth.svg"></span>
                                            <span class="pointer" value="nail_polish.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/nail_polish.svg')"><img src="http://visteco.in/images/emoticons/nail_polish.svg"></span>
                                            <span class="pointer" value="necktie.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/necktie.svg')"><img src="http://visteco.in/images/emoticons/necktie.svg"></span>
                                            <span class="pointer" value="nerd_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/nerd_face.svg')"><img src="http://visteco.in/images/emoticons/nerd_face.svg"></span>
                                            <span class="pointer" value="neutral_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/neutral_face.svg')"><img src="http://visteco.in/images/emoticons/neutral_face.svg"></span>
                                            <span class="pointer" value="nose.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/nose.svg')"><img src="http://visteco.in/images/emoticons/nose.svg"></span>
                                            <span class="pointer" value="ok_hand_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/ok_hand_sign.svg')"><img src="http://visteco.in/images/emoticons/ok_hand_sign.svg"></span>
                                            <span class="pointer" value="older_man.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/older_man.svg')"><img src="http://visteco.in/images/emoticons/older_man.svg"></span>
                                            <span class="pointer" value="older_woman.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/older_woman.svg')"><img src="http://visteco.in/images/emoticons/older_woman.svg"></span>
                                            <span class="pointer" value="open_hands_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/open_hands_sign.svg')"><img src="http://visteco.in/images/emoticons/open_hands_sign.svg"></span>
                                            <span class="pointer" value="pedestrian.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pedestrian.svg')"><img src="http://visteco.in/images/emoticons/pedestrian.svg"></span>
                                            <span class="pointer" value="pensive_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pensive_face.svg')"><img src="http://visteco.in/images/emoticons/pensive_face.svg"></span>
                                            <span class="pointer" value="persevering_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/persevering_face.svg')"><img src="http://visteco.in/images/emoticons/persevering_face.svg"></span>
                                            <span class="pointer" value="person_bowing_deeply.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_bowing_deeply.svg')"><img src="http://visteco.in/images/emoticons/person_bowing_deeply.svg"></span>
                                            <span class="pointer" value="person_frowning.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_frowning.svg')"><img src="http://visteco.in/images/emoticons/person_frowning.svg"></span>
                                            <span class="pointer" value="person_raising_both_hands_in_celebration.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_raising_both_hands_in_celebration.svg')"><img src="http://visteco.in/images/emoticons/person_raising_both_hands_in_celebration.svg"></span>
                                            <span class="pointer" value="person_with_blond_hair.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_with_blond_hair.svg')"><img src="http://visteco.in/images/emoticons/person_with_blond_hair.svg"></span>
                                            <span class="pointer" value="person_with_folded_hands.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_with_folded_hands.svg')"><img src="http://visteco.in/images/emoticons/person_with_folded_hands.svg"></span>
                                            <span class="pointer" value="person_with_pouting_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/person_with_pouting_face.svg')"><img src="http://visteco.in/images/emoticons/person_with_pouting_face.svg"></span>
                                            <span class="pointer" value="pile_of_poo.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pile_of_poo.svg')"><img src="http://visteco.in/images/emoticons/pile_of_poo.svg"></span>
                                            <span class="pointer" value="police_officer.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/police_officer.svg')"><img src="http://visteco.in/images/emoticons/police_officer.svg"></span>
                                            <span class="pointer" value="pouch.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pouch.svg')"><img src="http://visteco.in/images/emoticons/pouch.svg"></span>
                                            <span class="pointer" value="pouting_cat_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pouting_cat_face.svg')"><img src="http://visteco.in/images/emoticons/pouting_cat_face.svg"></span>
                                            <span class="pointer" value="pouting_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pouting_face.svg')"><img src="http://visteco.in/images/emoticons/pouting_face.svg"></span>
                                            <span class="pointer" value="pregnant_woman.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/pregnant_woman.svg')"><img src="http://visteco.in/images/emoticons/pregnant_woman.svg"></span>
                                            <span class="pointer" value="princess.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/princess.svg')"><img src="http://visteco.in/images/emoticons/princess.svg"></span>
                                            <span class="pointer" value="prince.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/prince.svg')"><img src="http://visteco.in/images/emoticons/prince.svg"></span>
                                            <span class="pointer" value="purse.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/purse.svg')"><img src="http://visteco.in/images/emoticons/purse.svg"></span>
                                            <span class="pointer" value="raised_back_of_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/raised_back_of_hand.svg')"><img src="http://visteco.in/images/emoticons/raised_back_of_hand.svg"></span>
                                            <span class="pointer" value="raised_fist.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/raised_fist.svg')"><img src="http://visteco.in/images/emoticons/raised_fist.svg"></span>
                                            <span class="pointer" value="raised_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/raised_hand.svg')"><img src="http://visteco.in/images/emoticons/raised_hand.svg"></span>
                                            <span class="pointer" value="raised_hand_with_fingers_splayed.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/raised_hand_with_fingers_splayed.svg')"><img src="http://visteco.in/images/emoticons/raised_hand_with_fingers_splayed.svg"></span>
                                            <span class="pointer" value="raised_hand_with_part_between_middle_and_ring_fingers.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/raised_hand_with_part_between_middle_and_ring_fingers.svg')"><img src="http://visteco.in/images/emoticons/raised_hand_with_part_between_middle_and_ring_fingers.svg"></span>
                                            <span class="pointer" value="relieved_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/relieved_face.svg')"><img src="http://visteco.in/images/emoticons/relieved_face.svg"></span>
                                            <span class="pointer" value="reversed_hand_with_middle_finger_extended.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/reversed_hand_with_middle_finger_extended.svg')"><img src="http://visteco.in/images/emoticons/reversed_hand_with_middle_finger_extended.svg"></span>
                                            <span class="pointer" value="right-facing_fist.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/right-facing_fist.svg')"><img src="http://visteco.in/images/emoticons/right-facing_fist.svg"></span>
                                            <span class="pointer" value="ring.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/ring.svg')"><img src="http://visteco.in/images/emoticons/ring.svg"></span>
                                            <span class="pointer" value="robot_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/robot_face.svg')"><img src="http://visteco.in/images/emoticons/robot_face.svg"></span>
                                            <span class="pointer" value="runner.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/runner.svg')"><img src="http://visteco.in/images/emoticons/runner.svg"></span>
                                            <span class="pointer" value="school_satchel.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/school_satchel.svg')"><img src="http://visteco.in/images/emoticons/school_satchel.svg"></span>
                                            <span class="pointer" value="selfie.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/selfie.svg')"><img src="http://visteco.in/images/emoticons/selfie.svg"></span>
                                            <span class="pointer" value="shrug.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/shrug.svg')"><img src="http://visteco.in/images/emoticons/shrug.svg"></span>
                                            <span class="pointer" value="sign_of_the_horns.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/sign_of_the_horns.svg')"><img src="http://visteco.in/images/emoticons/sign_of_the_horns.svg"></span>
                                            <span class="pointer" value="skull.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/skull.svg')"><img src="http://visteco.in/images/emoticons/skull.svg"></span>
                                            <span class="pointer" value="sleeping_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/sleeping_face.svg')"><img src="http://visteco.in/images/emoticons/sleeping_face.svg"></span>
                                            <span class="pointer" value="sleeping_symbol.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/sleeping_symbol.svg')"><img src="http://visteco.in/images/emoticons/sleeping_symbol.svg"></span>
                                            <span class="pointer" value="sleepy_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/sleepy_face.svg')"><img src="http://visteco.in/images/emoticons/sleepy_face.svg"></span>
                                            <span class="pointer" value="sleuth_or_spy.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/sleuth_or_spy.svg')"><img src="http://visteco.in/images/emoticons/sleuth_or_spy.svg"></span>
                                            <span class="pointer" value="slightly_frowning_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/slightly_frowning_face.svg')"><img src="http://visteco.in/images/emoticons/slightly_frowning_face.svg"></span>
                                            <span class="pointer" value="slightly_smiling_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/slightly_smiling_face.svg')"><img src="http://visteco.in/images/emoticons/slightly_smiling_face.svg"></span>
                                            <span class="pointer" value="smiling_cat_face_with_heart-shaped_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_cat_face_with_heart-shaped_eyes.svg')"><img src="http://visteco.in/images/emoticons/smiling_cat_face_with_heart-shaped_eyes.svg"></span>
                                            <span class="pointer" value="smiling_cat_face_with_open_mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_cat_face_with_open_mouth.svg')"><img src="http://visteco.in/images/emoticons/smiling_cat_face_with_open_mouth.svg"></span>
                                            <span class="pointer" value="smiling_face_with_halo.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_halo.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_halo.svg"></span>
                                            <span class="pointer" value="smiling_face_with_heart-shaped_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_heart-shaped_eyes.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_heart-shaped_eyes.svg"></span>
                                            <span class="pointer" value="smiling_face_with_horns.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_horns.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_horns.svg"></span>
                                            <span class="pointer" value="smiling_face_with_open_mouth_and_cold_sweat.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_cold_sweat.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_cold_sweat.svg"></span>
                                            <span class="pointer" value="smiling_face_with_open_mouth_and_smiling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_smiling_eyes.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_smiling_eyes.svg"></span>
                                            <span class="pointer" value="smiling_face_with_open_mouth_and_tightly-closed_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_tightly-closed_eyes.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_open_mouth_and_tightly-closed_eyes.svg"></span>
                                            <span class="pointer" value="smiling_face_with_open_mouth.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_open_mouth.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_open_mouth.svg"></span>
                                            <span class="pointer" value="smiling_face_with_smiling_eyes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_smiling_eyes.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_smiling_eyes.svg"></span>
                                            <span class="pointer" value="smiling_face_with_sunglasses.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smiling_face_with_sunglasses.svg')"><img src="http://visteco.in/images/emoticons/smiling_face_with_sunglasses.svg"></span>
                                            <span class="pointer" value="smirking_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/smirking_face.svg')"><img src="http://visteco.in/images/emoticons/smirking_face.svg"></span>
                                            <span class="pointer" value="speaking_head_in_silhouette.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/speaking_head_in_silhouette.svg')"><img src="http://visteco.in/images/emoticons/speaking_head_in_silhouette.svg"></span>
                                            <span class="pointer" value="thinking_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/thinking_face.svg')"><img src="http://visteco.in/images/emoticons/thinking_face.svg"></span>
                                            <span class="pointer" value="thumbs_down_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/thumbs_down_sign.svg')"><img src="http://visteco.in/images/emoticons/thumbs_down_sign.svg"></span>
                                            <span class="pointer" value="thumbs_up_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/thumbs_up_sign.svg')"><img src="http://visteco.in/images/emoticons/thumbs_up_sign.svg"></span>
                                            <span class="pointer" value="tired_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/tired_face.svg')"><img src="http://visteco.in/images/emoticons/tired_face.svg"></span>
                                            <span class="pointer" value="tongue.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/tongue.svg')"><img src="http://visteco.in/images/emoticons/tongue.svg"></span>
                                            <span class="pointer" value="top_hat.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/top_hat.svg')"><img src="http://visteco.in/images/emoticons/top_hat.svg"></span>
                                            <span class="pointer" value="t-shirt.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/t-shirt.svg')"><img src="http://visteco.in/images/emoticons/t-shirt.svg"></span>
                                            <span class="pointer" value="two_men_holding_hands.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/two_men_holding_hands.svg')"><img src="http://visteco.in/images/emoticons/two_men_holding_hands.svg"></span>
                                            <span class="pointer" value="two_women_holding_hands.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/two_women_holding_hands.svg')"><img src="http://visteco.in/images/emoticons/two_women_holding_hands.svg"></span>
                                            <span class="pointer" value="unamused_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/unamused_face.svg')"><img src="http://visteco.in/images/emoticons/unamused_face.svg"></span>
                                            <span class="pointer" value="upside-down_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/upside-down_face.svg')"><img src="http://visteco.in/images/emoticons/upside-down_face.svg"></span>
                                            <span class="pointer" value="victory_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/victory_hand.svg')"><img src="http://visteco.in/images/emoticons/victory_hand.svg"></span>
                                            <span class="pointer" value="waving_hand_sign.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/waving_hand_sign.svg')"><img src="http://visteco.in/images/emoticons/waving_hand_sign.svg"></span>
                                            <span class="pointer" value="weary_cat_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/weary_cat_face.svg')"><img src="http://visteco.in/images/emoticons/weary_cat_face.svg"></span>
                                            <span class="pointer" value="weary_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/weary_face.svg')"><img src="http://visteco.in/images/emoticons/weary_face.svg"></span>
                                            <span class="pointer" value="white_down_pointing_backhand_index.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_down_pointing_backhand_index.svg')"><img src="http://visteco.in/images/emoticons/white_down_pointing_backhand_index.svg"></span>
                                            <span class="pointer" value="white_frowning_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_frowning_face.svg')"><img src="http://visteco.in/images/emoticons/white_frowning_face.svg"></span>
                                            <span class="pointer" value="white_left_pointing_backhand_index.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_left_pointing_backhand_index.svg')"><img src="http://visteco.in/images/emoticons/white_left_pointing_backhand_index.svg"></span>
                                            <span class="pointer" value="white_right_pointing_backhand_index.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_right_pointing_backhand_index.svg')"><img src="http://visteco.in/images/emoticons/white_right_pointing_backhand_index.svg"></span>
                                            <span class="pointer" value="white_smiling_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_smiling_face.svg')"><img src="http://visteco.in/images/emoticons/white_smiling_face.svg"></span>
                                            <span class="pointer" value="white_up_pointing_backhand_index.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_up_pointing_backhand_index.svg')"><img src="http://visteco.in/images/emoticons/white_up_pointing_backhand_index.svg"></span>
                                            <span class="pointer" value="white_up_pointing_index.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/white_up_pointing_index.svg')"><img src="http://visteco.in/images/emoticons/white_up_pointing_index.svg"></span>
                                            <span class="pointer" value="winking_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/winking_face.svg')"><img src="http://visteco.in/images/emoticons/winking_face.svg"></span>
                                            <span class="pointer" value="womans_boots.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/womans_boots.svg')"><img src="http://visteco.in/images/emoticons/womans_boots.svg"></span>
                                            <span class="pointer" value="womans_clothes.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/womans_clothes.svg')"><img src="http://visteco.in/images/emoticons/womans_clothes.svg"></span>
                                            <span class="pointer" value="womans_hat.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/womans_hat.svg')"><img src="http://visteco.in/images/emoticons/womans_hat.svg"></span>
                                            <span class="pointer" value="womans_sandal.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/womans_sandal.svg')"><img src="http://visteco.in/images/emoticons/womans_sandal.svg"></span>
                                            <span class="pointer" value="woman.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/woman.svg')"><img src="http://visteco.in/images/emoticons/woman.svg"></span>
                                            <span class="pointer" value="woman_with_bunny_ears.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/woman_with_bunny_ears.svg')"><img src="http://visteco.in/images/emoticons/woman_with_bunny_ears.svg"></span>
                                            <span class="pointer" value="worried_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/worried_face.svg')"><img src="http://visteco.in/images/emoticons/worried_face.svg"></span>
                                            <span class="pointer" value="writing_hand.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/writing_hand.svg')"><img src="http://visteco.in/images/emoticons/writing_hand.svg"></span>
                                            <span class="pointer" value="zipper-mouth_face.svg" onclick="addEmojies('post_cmnt_15','http://visteco.in/images/emoticons/zipper-mouth_face.svg')"><img src="http://visteco.in/images/emoticons/zipper-mouth_face.svg"></span>
      
    </div>
  </div>
</div>

                                            
                                            
                                   